version: '3.1'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/src
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web

  php:
    image: php:8.1-fpm
    volumes:
      - ./src:/src
    networks:
      - web

networks:
  web:
    driver: bridge